participants:

    Calculix2:
        interfaces:
        - nodes-mesh: Calculix_Mesh2
          patch: surface
          read-data: [Forces0]
          write-data: [Displacements0]
#          read-data: [Displacements0]
#          write-data: [Forces0]
          
precice-config-file: ../precice-config.xml
